### ISSUE TITLE
Cannot Read Url of Null

### ISSUE THREAD

**Issue by jonathanRinciari** [AsyncOptics/async-optics#35]
I am trying to use this in one of my projects, and I seem to get an error on line 84 of asynMonitor.js that says cannot read URL of null. I have set this up in my server.js file as such

`const { asyncMonitor, pkgMonitor } = require('async-optics');
asyncMonitor(8100);
pkgMonitor(path.join(__dirname, '../package.json'));
`
If you have any recommendations maybe I set this up incorrectly.

**Comment by wupenghe92** [comment]
hi, thank you for letting us know. Can you try to update the package and let us know if there are other issues?

**Comment by jonathanRinciari** [comment]
`typeError: Cannot read property 'constructor' of null
    at AsyncHook.init (/Users/jonrinciari/Code/homereport/hyperlocal/api/node_modules/async-optics/asyncMonitor.js:91:42)
    at emitInitNative (internal/async_hooks.js:130:43)
    at emitInitScript (internal/async_hooks.js:309:3)
    at new TickObject (internal/process/next_tick.js:177:9)`

Thanks for getting back to me quickly

**Comment by jonathanRinciari** [comment]
similar to what you did for line 84
`if(resource.args && resource.args[0] && resource.args[0].constructor.name === 'Socket'`

fixes the issue
